
name: Build

on: 
  push: 
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/          
      - run: npm install
      - run: npm install -g typescript@3.7.3
      - run: node ./generator.js
      - run: tsc
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - run: node ./png/change-name.js
      - run: node ./generate-png.js
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - run: node ./png/undo.js
